//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34209
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dguv.Validator.Properties {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dguv.Validator.Properties.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es muss eine BBNR-UV angegeben werden. ähnelt.
        /// </summary>
        internal static string CheckBbnrUvError {
            get {
                return ResourceManager.GetString("CheckBbnrUvError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es muss ein Name für eine BBNR-UV angegeben werden. ähnelt.
        /// </summary>
        internal static string CheckBbnrUvNameError {
            get {
                return ResourceManager.GetString("CheckBbnrUvNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Wert von maxLength darf nicht kleiner als -1 oder minLength sein und darf nicht den Wert 0 haben. ähnelt.
        /// </summary>
        internal static string CheckMaxLengthError {
            get {
                return ResourceManager.GetString("CheckMaxLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Wert von minLength darf nicht kleiner als -1 sein. ähnelt.
        /// </summary>
        internal static string CheckMinLengthError {
            get {
                return ResourceManager.GetString("CheckMinLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ungültige BBNR-UV ähnelt.
        /// </summary>
        internal static string StatusInvalidBbnrUv {
            get {
                return ResourceManager.GetString("StatusInvalidBbnrUv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Mitgliedsnummer enthält ein oder mehrere ungültige Zeichen. Erlaubt sind nur folgende Zeichen: &quot;{0}&quot; ähnelt.
        /// </summary>
        internal static string StatusMemberIdInvalidCharacter {
            get {
                return ResourceManager.GetString("StatusMemberIdInvalidCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es muss eine Mitgliedsnummer angegeben werden. ähnelt.
        /// </summary>
        internal static string StatusMemberIdMissing {
            get {
                return ResourceManager.GetString("StatusMemberIdMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Mitgliedsnummer ist zu lang. Sie darf höchstens eine Länge von {0} Zeichen haben. ähnelt.
        /// </summary>
        internal static string StatusMemberIdTooLong {
            get {
                return ResourceManager.GetString("StatusMemberIdTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Mitgliedsnummer ist zu kurz. Sie muss eine Länge von mindestens {0} Zeichen haben. ähnelt.
        /// </summary>
        internal static string StatusMemberIdTooShort {
            get {
                return ResourceManager.GetString("StatusMemberIdTooShort", resourceCulture);
            }
        }
    }
}
